#!/usr/bin/with-contenv bash
# Happier startup script
# Supports two roles controlled by the CONTAINER_ROLE env var:
#   server  — starts the relay server + web UI (default)
#   agent   — configures the CLI/daemon to connect to a remote relay server

set -euo pipefail

ROLE="${CONTAINER_ROLE:-server}"

case "$ROLE" in
  server)
    echo "=== Happier: SERVER mode ==="

    # Auto-migrate the SQLite database on first startup (creates tables if missing).
    export HAPPIER_SQLITE_AUTO_MIGRATE=true
    export DATABASE_URL="file:/app/.happy/server-light/happier-server-light.sqlite"

    # Ensure Prisma migrations are available where the server expects them.
    # They are pre-copied at build time; this is a runtime fallback for version
    # bumps where the cache directory contains a newer path.
    if [ ! -d "/app/.happy/server-light/migrations/sqlite" ]; then
      MIGRATIONS_SRC=$(find "/app/.cache/happier/server" -path "*/prisma/sqlite/migrations" -type d 2>/dev/null | head -1)
      if [ -n "$MIGRATIONS_SRC" ]; then
        mkdir -p /app/.happy/server-light/migrations
        cp -r "$MIGRATIONS_SRC" /app/.happy/server-light/migrations/sqlite
        echo "Migrations copied at runtime (fallback)"
      fi
    fi

    echo "Starting Happier relay server on http://0.0.0.0:3005"
    happier-server --ui &
    ;;

  agent)
    echo "=== Happier: AGENT mode ==="

    # Point the CLI and daemon at the relay server.
    export HAPPIER_SERVER_URL="${HAPPIER_SERVER_URL:-http://happier-server:3005}"

    # Ensure the config directory exists.
    mkdir -p "$HOME/.happier"

    # Check whether this agent has already been authenticated with the server
    # by looking for the local key material generated by `happier auth login`.
    if [ -f "$HOME/.happier/access.key" ]; then
      echo "Happier agent is authenticated with $HAPPIER_SERVER_URL"
      echo "Starting Happier daemon..."
      happier --server-url "$HAPPIER_SERVER_URL" daemon start || true
    else
      echo "============================================================"
      echo "  Happier Agent — Not Yet Authenticated"
      echo "============================================================"
      echo ""
      echo "Relay server URL: $HAPPIER_SERVER_URL"
      echo ""
      echo "Connect this agent to the relay server:"
      echo ""
      echo "  1. Run the interactive auth command:"
      echo "     happier --server-url $HAPPIER_SERVER_URL auth login"
      echo ""
      echo "  2. Follow the pairing instructions shown on screen."
      echo ""
      echo "  3. Start the daemon (persistent background sync):"
      echo "     happier --server-url $HAPPIER_SERVER_URL daemon start"
      echo ""
      echo "  4. Launch a Claude Code session through Happier:"
      echo "     happier --server-url $HAPPIER_SERVER_URL claude"
      echo ""
      echo "These steps only need to be done once per agent container."
      echo "============================================================"
    fi
    ;;

  *)
    echo "ERROR: Unknown CONTAINER_ROLE='$ROLE'. Supported: server, agent"
    exit 1
    ;;
esac
