services:
  vsclaude-dev-test:
    image: vscode-claude:test-fix
    container_name: vsclaude-dev-test
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - SUDO_PASSWORD=abc
      - DEFAULT_WORKSPACE=/workspace
      - PWA_APPNAME=code-server
      - CLAUDE_CODE_PERMISSION_MODE=bypassPermissions
      - CLAUDE_MARKETPLACES=anthropics/claude-plugins-official
      - CLAUDE_PLUGINS=superpowers
      - GIT_REPO_URL=https://github.com/TylerCollison/vscode-claude.git
      - GIT_BRANCH_NAME=happier
      - GIT_AUTHOR_NAME="TylerCollison"
      - GIT_AUTHOR_EMAIL="tylerc2089@hotmail.com"
      - GIT_COMMITTER_NAME="TylerCollison"
      - GIT_COMMITTER_EMAIL="tylerc2089@hotmail.com"
      - GIT_SSL_NO_VERIFY=true
      - GIT_CONFIG_COUNT=1
      - GIT_CONFIG_KEY_0=safe.directory
      - GIT_CONFIG_VALUE_0="*"
      - HAPPIER_MODE=agent
      - LOGGING=verbose
      - HAPPIER_SERVER_URL=https://192.168.1.245:3005/
      - HAPPIER_ACCESS_KEY={"encryption":{"publicKey":"F3Mlax3S9MaGTkKc86Gn9SO+AKABg9ZAJhmmay1POR0=","machineKey":"OtM56jud1Xh4sQqFF/R+d+uIJkI6fKPTzy/sVK0y3XQ="},"token":"eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJjbXM2Z2VmdngwMDAxbnRkYWtyZDM1NG80Iiwic2Vzc2lvbiI6ImNtczZnZGM2NTAwMDBudGRhdjBqY2pjb3EiLCJpYXQiOjE3ODUzNTE4NjMsIm5iZiI6MTc4NTM1MTg2MywiaXNzIjoiaGFuZHkiLCJqdGkiOiIxNTkzMjU2Mi1kMGI3LTQ0NTEtODEwOS02MTUxMzQwNmFhYTgifQ.3mgX-8J5oS1Cfd5szw_Q7bB178kJQFBYGtFb2DDTLwcRAystKXkGkJe11Q70kA6o0j45yLYIfUAM-IIRE2DfAQ"}
    ports:
      - "3444:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
